server:
  tomcat:
    max-http-post-size: -1
spring:
  profiles:
    active: dev
  application:
    name: medical
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  datasource:
    maxActive: 20
    initialSize: 5
    minIdle: 5
    maxWait: 6000
    maxPoolPreparedStatementPerConnectionSize: 20
    timeBetweenEvictionRunsMillis: 6000
    driver-class-name: com.mysql.jdbc.Driver     #com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true    #当遇到同样名字的时候，是否允许覆盖注册
  cache:
    type: redis  # 可选 redis、none、ehcache
  redis:
     timeout: 20000     # 链接超时时间（毫秒）
     lettuce:
       pool:
         max-idle: 8        # 最大空闲连接
         min-idle: 0        # 最小空闲链接
         max-active: 8      # 最大连接数（负数表示没有限制）
         max-wait: -1       # 最大阻塞等待时间（负数表示没有限制）
  #院版配置
  hosconfig:
    hos-token-url: http://61.172.179.73:41150 # 获取院版token的url
    hos-data-server-url: http://61.172.179.73:41149 #获取院版数据的url
    app-id: Oh_Newtouch_Clinic # 院版对应的appid
    organize-id: 6d5752a7-234a-403e-aa1c-df8b45d3469f #院版对应的organizeid
  #医保配置
  medicare:
    check: false #开启医保配置
    province:     #医保省份
    url:          #接口地址

logging:
  level:
    com.geeke.gen.dao.*: debug
    com.geeke.admin.dao.*: debug
    com.geeke.sys.dao.*: debug
    org.camunda: debug
    com.geeke.gen: debug
# mybatis-plus配置
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: FULL
    map-underscore-to-camel-case: true
    default-executor-type: SIMPLE
    local-cache-scope: SESSION

mybatis-plus:
  configuration:
    global-config:
      db-config:
        id-type: auto
    mapper-locations: classpath:/mapper/**/*.xml
    # 其他 MyBatis-Plus 配置项

genConfigure:
  rootPath: C:\Users\developer\IdeaProjects\medical #代码生成地址配置
  dbName: mysql                          #数据库类型:  mysql/oracle/mssql




